apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
      description: shared pvc for providing access to other tasks input/output
  params:
    - name: CONTEXT_DIR
      type: string
      default: "."
      description: The path where package.json of the project is defined.
    - name: IMAGE_NPM
      type: string
      default: node:14.17.3-slim
      description: The node image you want to use.
    - name: REGISTRY_NPM
      default: https://alm-npmjs.misys.global.ad/nexus/repository/npm_group/
      # default: https://nexus.finastra.com/nexus/repository/npm_group/
      # default: http://nexus.l21d31708530003.local/repository/lab-npm/
      description: npm registry used for downloading prereqs
  steps:
    - name: npm-config-install
      image: $(params.IMAGE_NPM)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        npm config --global set prefix $(workspaces.source.path)/$(params.CONTEXT_DIR)
        npm config --global set strict-ssl false
        npm config --global set registry $(params.REGISTRY_NPM)
        npm --registry=$(params.REGISTRY_NPM) install
        npm fund
      env:
        - name: CI
          value: "true"
    - name: npm-build
      image: $(params.IMAGE_NPM)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        npm run build